
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nykytamcdonald
 */
public class PlaylistGUI extends javax.swing.JFrame {
    
    private LikedSongPlaylists likedSongs;
    private Song song;
    private GeneralPlaylists generalPlaylist1;
    private GeneralPlaylists generalPlaylist2;
    private String songName;
    private String artistName;
    private String albumName;

    /**
     * Creates new form PlaylistGUI
     */
    public PlaylistGUI() {
        initComponents();
        likedSongs = new LikedSongPlaylists();
        generalPlaylist1 = new GeneralPlaylists(likedSongs);
        generalPlaylist2 = new GeneralPlaylists(likedSongs);
    }
    
    private void getLikedData(){
        songName = lblSongName.getText();
        artistName = lblArtistName.getText();
        albumName = lblAlbumName.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblSongName = new javax.swing.JTextField();
        lblArtistName = new javax.swing.JTextField();
        lblAlbumName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddLiked = new javax.swing.JButton();
        btnDeleteLiked = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPrintLiked = new javax.swing.JButton();
        btnClearLiked = new javax.swing.JButton();
        btnSearchLiked = new javax.swing.JButton();
        lblSearchLiked = new javax.swing.JTextField();
        genericTitle1 = new javax.swing.JLabel();
        genericTitle2 = new javax.swing.JLabel();
        btnNamePlaylist1 = new javax.swing.JButton();
        btnNamePlaylist2 = new javax.swing.JToggleButton();
        lblNameGeneric2 = new javax.swing.JTextField();
        lblNameGeneric1 = new javax.swing.JTextField();
        btnAddToGeneric1 = new javax.swing.JButton();
        btnAddToGeneric2 = new javax.swing.JToggleButton();
        btnPlaceLike1 = new javax.swing.JToggleButton();
        btnPlaceLike2 = new javax.swing.JToggleButton();
        lblPlaceLike2 = new javax.swing.JTextField();
        lblPlaceLike1 = new javax.swing.JTextField();
        btnRemoveLiked1 = new javax.swing.JButton();
        btnRemoveLiked2 = new javax.swing.JButton();
        lblRemoveLiked2 = new javax.swing.JTextField();
        lblRemoveLiked1 = new javax.swing.JTextField();
        btnPrintGeneral1 = new javax.swing.JToggleButton();
        btnPrintGeneral2 = new javax.swing.JToggleButton();
        btnMoveGeneric1 = new javax.swing.JButton();
        btnMoveGeneric2 = new javax.swing.JButton();
        lblMoveFrom1 = new javax.swing.JTextField();
        lblMoveFrom2 = new javax.swing.JTextField();
        lblMoveTo1 = new javax.swing.JTextField();
        lblMoveTo2 = new javax.swing.JTextField();
        btnRepeat1 = new javax.swing.JButton();
        btnRepeat2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblYes1 = new javax.swing.JRadioButton();
        lblNo1 = new javax.swing.JRadioButton();
        lblNo2 = new javax.swing.JRadioButton();
        lblYes2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblPostMessages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblArtistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblArtistNameActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Song Name:");

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Album Name:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Artist Name:");

        btnAddLiked.setText("Add to Liked");
        btnAddLiked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLikedActionPerformed(evt);
            }
        });

        btnDeleteLiked.setText("Delete Liked Song");
        btnDeleteLiked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLikedActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("Liked Songs Playlist");

        btnPrintLiked.setText("Print Liked Playlist");
        btnPrintLiked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintLikedActionPerformed(evt);
            }
        });

        btnClearLiked.setText("Clear");
        btnClearLiked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLikedActionPerformed(evt);
            }
        });

        btnSearchLiked.setText("Search Liked Song");
        btnSearchLiked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLikedActionPerformed(evt);
            }
        });

        genericTitle1.setForeground(new java.awt.Color(0, 0, 0));
        genericTitle1.setText("Generic Playlist #1");

        genericTitle2.setForeground(new java.awt.Color(0, 0, 0));
        genericTitle2.setText("Generic Playlist #2");

        btnNamePlaylist1.setText("Name Playlist");
        btnNamePlaylist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamePlaylist1ActionPerformed(evt);
            }
        });

        btnNamePlaylist2.setText("Name Playlist");
        btnNamePlaylist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamePlaylist2ActionPerformed(evt);
            }
        });

        lblNameGeneric2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNameGeneric2ActionPerformed(evt);
            }
        });

        btnAddToGeneric1.setText("Add Liked Song");
        btnAddToGeneric1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToGeneric1ActionPerformed(evt);
            }
        });

        btnAddToGeneric2.setText("Add Liked Song");
        btnAddToGeneric2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToGeneric2ActionPerformed(evt);
            }
        });

        btnPlaceLike1.setText("Add to Position");
        btnPlaceLike1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceLike1ActionPerformed(evt);
            }
        });

        btnPlaceLike2.setText("Add to Position");
        btnPlaceLike2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceLike2ActionPerformed(evt);
            }
        });

        btnRemoveLiked1.setText("Remove");
        btnRemoveLiked1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLiked1ActionPerformed(evt);
            }
        });

        btnRemoveLiked2.setText("Remove");
        btnRemoveLiked2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLiked2ActionPerformed(evt);
            }
        });

        btnPrintGeneral1.setText("Print Playlist");
        btnPrintGeneral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintGeneral1ActionPerformed(evt);
            }
        });

        btnPrintGeneral2.setText("Print Playlist");
        btnPrintGeneral2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintGeneral2ActionPerformed(evt);
            }
        });

        btnMoveGeneric1.setText("Move Song");
        btnMoveGeneric1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveGeneric1ActionPerformed(evt);
            }
        });

        btnMoveGeneric2.setText("Move Song");
        btnMoveGeneric2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveGeneric2ActionPerformed(evt);
            }
        });

        lblMoveFrom1.setText("From");

        lblMoveFrom2.setText("From");

        lblMoveTo1.setText("To");

        lblMoveTo2.setText("To");

        btnRepeat1.setText("Repeat");
        buttonGroup1.add(btnRepeat1);
        btnRepeat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepeat1ActionPerformed(evt);
            }
        });

        btnRepeat2.setText("Repeat");
        buttonGroup2.add(btnRepeat2);
        btnRepeat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepeat2ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Message Window ");

        buttonGroup1.add(lblYes1);
        lblYes1.setText("Yes");

        buttonGroup1.add(lblNo1);
        lblNo1.setText("No");

        buttonGroup2.add(lblNo2);
        lblNo2.setText("No");

        buttonGroup2.add(lblYes2);
        lblYes2.setText("Yes");

        lblPostMessages.setColumns(20);
        lblPostMessages.setRows(5);
        jScrollPane1.setViewportView(lblPostMessages);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(genericTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(genericTitle2)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnAddLiked))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAlbumName)
                                            .addComponent(lblArtistName)
                                            .addComponent(lblSongName)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSearchLiked)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(lblSearchLiked))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnDeleteLiked, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btnPrintLiked, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnClearLiked, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(47, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAddToGeneric1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNameGeneric1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPlaceLike1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblRemoveLiked1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPrintGeneral1))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRemoveLiked1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnPlaceLike1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnNamePlaylist1, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(64, 64, 64)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(371, 371, 371)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddToGeneric2)
                                    .addComponent(btnRemoveLiked2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNamePlaylist2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(btnMoveGeneric1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMoveFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(lblYes1)
                                        .addGap(27, 27, 27)
                                        .addComponent(lblNo1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMoveTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnMoveGeneric2)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMoveFrom2))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblPlaceLike2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblRemoveLiked2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblNameGeneric2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnPrintGeneral2))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnRepeat1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblYes2)
                                        .addGap(27, 27, 27)
                                        .addComponent(lblNo2)
                                        .addGap(30, 30, 30)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(btnPlaceLike2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRepeat2)
                                            .addComponent(lblMoveTo2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(13, 13, 13)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlbumName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddLiked)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteLiked)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchLiked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchLiked))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClearLiked)
                            .addComponent(btnPrintLiked)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genericTitle2)
                    .addComponent(genericTitle1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameGeneric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNamePlaylist1)
                    .addComponent(lblNameGeneric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNamePlaylist2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToGeneric2)
                    .addComponent(btnAddToGeneric1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceLike1)
                    .addComponent(btnPlaceLike2)
                    .addComponent(lblPlaceLike2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlaceLike1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveLiked1)
                    .addComponent(btnRemoveLiked2)
                    .addComponent(lblRemoveLiked2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemoveLiked1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrintGeneral1)
                    .addComponent(btnPrintGeneral2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoveGeneric1)
                    .addComponent(btnMoveGeneric2)
                    .addComponent(lblMoveFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoveFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoveTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoveTo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYes2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRepeat1)
                        .addComponent(btnRepeat2)
                        .addComponent(lblYes1)
                        .addComponent(lblNo1)
                        .addComponent(lblNo2)))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveLiked2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveLiked2ActionPerformed
        // TODO add your handling code here:
        try{
            int removeIndex = Integer.parseInt(lblRemoveLiked2.getText());
            Song removedSong = generalPlaylist2.get(removeIndex);
            generalPlaylist2.remove(removeIndex);
            if(removedSong == null){
                lblPostMessages.setText("Nothing to remove");
            } else {
                lblPostMessages.setText("Removed " + removedSong);
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number");
        }
    }//GEN-LAST:event_btnRemoveLiked2ActionPerformed

    private void btnRemoveLiked1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveLiked1ActionPerformed
        // TODO add your handling code here:
        try{
            int removeIndex = Integer.parseInt(lblRemoveLiked1.getText());
            Song removedSong = generalPlaylist1.get(removeIndex);
            generalPlaylist1.remove(removeIndex);
            if(removedSong == null){
                lblPostMessages.setText("Nothing to remove");
            } else {
                lblPostMessages.setText("Removed " + removedSong);
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number");
        }
    }//GEN-LAST:event_btnRemoveLiked1ActionPerformed

    private void lblNameGeneric2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNameGeneric2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNameGeneric2ActionPerformed

    private void btnDeleteLikedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLikedActionPerformed
        // TODO add your handling code here:
        Song storedSong = null;
        storedSong = likedSongs.pop();
        if(storedSong == null){
            lblPostMessages.setText("Nothing to remove");
        } else {
            lblPostMessages.setText(storedSong + " has been removed");
        }
    }//GEN-LAST:event_btnDeleteLikedActionPerformed

    private void btnAddLikedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLikedActionPerformed
        // TODO add your handling code here:
        getLikedData();
        if(songName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Song Name");
        } else if (albumName.isEmpty()) {
            song = new Song(songName,artistName);
        } else {
            song = new Song(songName, artistName, albumName);
        }
        if(!(songName.isEmpty())){
            likedSongs.push(song);
            lblPostMessages.setText("Song Added to Liked");
        }
    }//GEN-LAST:event_btnAddLikedActionPerformed

    private void lblArtistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblArtistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblArtistNameActionPerformed

    private void btnMoveGeneric1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveGeneric1ActionPerformed
        // TODO add your handling code here:
        try{
            int fromIndex = Integer.parseInt(lblMoveFrom1.getText());
            int toIndex = Integer.parseInt(lblMoveTo1.getText());
            Song songIndex = generalPlaylist1.get(fromIndex);
            generalPlaylist1.move(fromIndex, toIndex);
            lblPostMessages.setText("Moved " + songIndex + " from " + fromIndex + " to " + toIndex);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number");
        }
    }//GEN-LAST:event_btnMoveGeneric1ActionPerformed

    private void btnRepeat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepeat1ActionPerformed
        // TODO add your handling code here:
        
        String pickAnswer;
        
        if(lblYes1.isSelected()){
            pickAnswer = lblYes1.getText();
            lblPostMessages.setText(generalPlaylist1.repeat(pickAnswer));                 
        } else if (lblNo1.isSelected()){
            pickAnswer = lblNo1.getText();
            lblPostMessages.setText(generalPlaylist1.repeat(pickAnswer));
        } else {
            JOptionPane.showMessageDialog(null,"Please select yes or no");
        } 
        
    }//GEN-LAST:event_btnRepeat1ActionPerformed

    private void btnSearchLikedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLikedActionPerformed
        // TODO add your handling code here:
        String searchName = lblSearchLiked.getText();
        lblPostMessages.setText(likedSongs.searchSong(searchName));
    }//GEN-LAST:event_btnSearchLikedActionPerformed

    private void btnPrintLikedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintLikedActionPerformed
        // TODO add your handling code here:
        lblPostMessages.setText(likedSongs.printPlaylist());
    }//GEN-LAST:event_btnPrintLikedActionPerformed

    private void btnClearLikedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLikedActionPerformed
        // TODO add your handling code here:
        likedSongs.clear();
        lblPostMessages.setText("Playlist cleared");
    }//GEN-LAST:event_btnClearLikedActionPerformed

    private void btnNamePlaylist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamePlaylist1ActionPerformed
        // TODO add your handling code here:
        String nameOfGeneric1 = lblNameGeneric1.getText();
        genericTitle1.setText(nameOfGeneric1 + " Playlist");
    }//GEN-LAST:event_btnNamePlaylist1ActionPerformed

    private void btnAddToGeneric1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToGeneric1ActionPerformed
        // TODO add your handling code here:
        if(!(likedSongs.isEmpty())){
            generalPlaylist1.add();
            lblPostMessages.setText(generalPlaylist1.get(generalPlaylist1.size()) + " added");
        } else {
            JOptionPane.showMessageDialog(null, "No Songs in liked Playlist");
        }
    }//GEN-LAST:event_btnAddToGeneric1ActionPerformed

    private void btnPlaceLike1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceLike1ActionPerformed
        // TODO add your handling code here:
        if(likedSongs.isEmpty()){
            JOptionPane.showMessageDialog(null, "No Songs in liked Playlist");
        } else if (generalPlaylist1 == null) {
            JOptionPane.showMessageDialog(null, "No Songs. Please Add Liked Song");
        } else {
            try{
            int addIndex = Integer.parseInt(lblPlaceLike1.getText());
            generalPlaylist1.add(addIndex);
            lblPostMessages.setText("Song added");
            } catch (NumberFormatException a){
                JOptionPane.showMessageDialog(null, "Please enter a number");
            }
        }
    }//GEN-LAST:event_btnPlaceLike1ActionPerformed

    private void btnPrintGeneral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintGeneral1ActionPerformed
        // TODO add your handling code here:
        lblPostMessages.setText(generalPlaylist1.printPlaylist());       
    }//GEN-LAST:event_btnPrintGeneral1ActionPerformed

    private void btnNamePlaylist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamePlaylist2ActionPerformed
        // TODO add your handling code here:
        String nameOfGeneric2 = lblNameGeneric2.getText();
        genericTitle2.setText(nameOfGeneric2 + " Playlist");
    }//GEN-LAST:event_btnNamePlaylist2ActionPerformed

    private void btnAddToGeneric2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToGeneric2ActionPerformed
        // TODO add your handling code here:
        if(!(likedSongs.isEmpty())){
            generalPlaylist2.add();
            lblPostMessages.setText(generalPlaylist2.get(generalPlaylist2.size()) + " added");
        } else {
            JOptionPane.showMessageDialog(null, "No Songs in liked Playlist");
        }
    }//GEN-LAST:event_btnAddToGeneric2ActionPerformed

    private void btnPlaceLike2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceLike2ActionPerformed
        // TODO add your handling code here:
         if(likedSongs.isEmpty()){
            JOptionPane.showMessageDialog(null, "No Songs in liked Playlist");
        } else if (generalPlaylist2 == null) {
            JOptionPane.showMessageDialog(null, "No Songs. Please Add Liked Song");
        } else {
            try{
            int addIndex = Integer.parseInt(lblPlaceLike2.getText());
            generalPlaylist2.add(addIndex);
            lblPostMessages.setText("Song added");
            } catch (NumberFormatException a){
                JOptionPane.showMessageDialog(null, "Please enter a number");
            }
        }
    }//GEN-LAST:event_btnPlaceLike2ActionPerformed

    private void btnPrintGeneral2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintGeneral2ActionPerformed
        // TODO add your handling code here:
        lblPostMessages.setText(generalPlaylist2.printPlaylist());
    }//GEN-LAST:event_btnPrintGeneral2ActionPerformed

    private void btnMoveGeneric2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveGeneric2ActionPerformed
        // TODO add your handling code here:
         try{
            int fromIndex = Integer.parseInt(lblMoveFrom2.getText());
            int toIndex = Integer.parseInt(lblMoveTo2.getText());
            Song songIndex = generalPlaylist2.get(fromIndex);
            generalPlaylist2.move(fromIndex, toIndex);
            lblPostMessages.setText("Moved " + songIndex + " from " + fromIndex + " to " + toIndex);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number");
        }
    }//GEN-LAST:event_btnMoveGeneric2ActionPerformed

    private void btnRepeat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepeat2ActionPerformed
        // TODO add your handling code here:
        String pickAnswer;
        
        if(lblYes2.isSelected()){
            pickAnswer = lblYes2.getText();
            lblPostMessages.setText(generalPlaylist2.repeat(pickAnswer));                 
        } else if (lblNo2.isSelected()){
            pickAnswer = lblNo2.getText();
            lblPostMessages.setText(generalPlaylist2.repeat(pickAnswer));
        } else {
            JOptionPane.showMessageDialog(null,"Please select yes or no");
        } 
    }//GEN-LAST:event_btnRepeat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLiked;
    private javax.swing.JButton btnAddToGeneric1;
    private javax.swing.JToggleButton btnAddToGeneric2;
    private javax.swing.JButton btnClearLiked;
    private javax.swing.JButton btnDeleteLiked;
    private javax.swing.JButton btnMoveGeneric1;
    private javax.swing.JButton btnMoveGeneric2;
    private javax.swing.JButton btnNamePlaylist1;
    private javax.swing.JToggleButton btnNamePlaylist2;
    private javax.swing.JToggleButton btnPlaceLike1;
    private javax.swing.JToggleButton btnPlaceLike2;
    private javax.swing.JToggleButton btnPrintGeneral1;
    private javax.swing.JToggleButton btnPrintGeneral2;
    private javax.swing.JButton btnPrintLiked;
    private javax.swing.JButton btnRemoveLiked1;
    private javax.swing.JButton btnRemoveLiked2;
    private javax.swing.JButton btnRepeat1;
    private javax.swing.JButton btnRepeat2;
    private javax.swing.JButton btnSearchLiked;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel genericTitle1;
    private javax.swing.JLabel genericTitle2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblAlbumName;
    private javax.swing.JTextField lblArtistName;
    private javax.swing.JTextField lblMoveFrom1;
    private javax.swing.JTextField lblMoveFrom2;
    private javax.swing.JTextField lblMoveTo1;
    private javax.swing.JTextField lblMoveTo2;
    private javax.swing.JTextField lblNameGeneric1;
    private javax.swing.JTextField lblNameGeneric2;
    private javax.swing.JRadioButton lblNo1;
    private javax.swing.JRadioButton lblNo2;
    private javax.swing.JTextField lblPlaceLike1;
    private javax.swing.JTextField lblPlaceLike2;
    private javax.swing.JTextArea lblPostMessages;
    private javax.swing.JTextField lblRemoveLiked1;
    private javax.swing.JTextField lblRemoveLiked2;
    private javax.swing.JTextField lblSearchLiked;
    private javax.swing.JTextField lblSongName;
    private javax.swing.JRadioButton lblYes1;
    private javax.swing.JRadioButton lblYes2;
    // End of variables declaration//GEN-END:variables
}
